# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../GUI/mainwindow.ui'
#
# Created: Wed Jun  1 22:46:47 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.View1 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View1.setGeometry(QtCore.QRect(260, 0, 256, 256))
        self.View1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View1.setObjectName("View1")
        self.View2 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View2.setGeometry(QtCore.QRect(530, 0, 256, 256))
        self.View2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View2.setObjectName("View2")
        self.View4 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View4.setGeometry(QtCore.QRect(530, 270, 256, 256))
        self.View4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View4.setObjectName("View4")
        self.View3 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View3.setGeometry(QtCore.QRect(260, 270, 256, 256))
        self.View3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View3.setObjectName("View3")
        self.QTab = QtWidgets.QTabWidget(self.centralWidget)
        self.QTab.setGeometry(QtCore.QRect(10, 0, 230, 321))
        self.QTab.setObjectName("QTab")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.GrayvalueScrollBar = QtWidgets.QScrollBar(self.tab1)
        self.GrayvalueScrollBar.setGeometry(QtCore.QRect(210, 0, 16, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GrayvalueScrollBar.sizePolicy().hasHeightForWidth())
        self.GrayvalueScrollBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.GrayvalueScrollBar.setFont(font)
        self.GrayvalueScrollBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.GrayvalueScrollBar.setMouseTracking(False)
        self.GrayvalueScrollBar.setMaximum(255)
        self.GrayvalueScrollBar.setPageStep(8)
        self.GrayvalueScrollBar.setProperty("value", 0)
        self.GrayvalueScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.GrayvalueScrollBar.setObjectName("GrayvalueScrollBar")
        self.histogram = QtWidgets.QPushButton(self.tab1)
        self.histogram.setGeometry(QtCore.QRect(20, 60, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram.sizePolicy().hasHeightForWidth())
        self.histogram.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histogram.setFont(font)
        self.histogram.setObjectName("histogram")
        self.OTSU = QtWidgets.QPushButton(self.tab1)
        self.OTSU.setGeometry(QtCore.QRect(20, 120, 88, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OTSU.setFont(font)
        self.OTSU.setObjectName("OTSU")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setGeometry(QtCore.QRect(167, 130, 41, 20))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setContentsMargins(0, 0, 0, 0)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.QTab.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.MeanFilter = QtWidgets.QPushButton(self.tab2)
        self.MeanFilter.setGeometry(QtCore.QRect(40, 30, 88, 27))
        self.MeanFilter.setObjectName("MeanFilter")
        self.MedianFilter = QtWidgets.QPushButton(self.tab2)
        self.MedianFilter.setGeometry(QtCore.QRect(40, 60, 88, 27))
        self.MedianFilter.setObjectName("MedianFilter")
        self.GaussianFilter = QtWidgets.QPushButton(self.tab2)
        self.GaussianFilter.setGeometry(QtCore.QRect(40, 90, 88, 27))
        self.GaussianFilter.setObjectName("GaussianFilter")
        self.line_2 = QtWidgets.QFrame(self.tab2)
        self.line_2.setGeometry(QtCore.QRect(0, 150, 231, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab2)
        self.radioButton_2.setGeometry(QtCore.QRect(160, 70, 61, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton = QtWidgets.QRadioButton(self.tab2)
        self.radioButton.setGeometry(QtCore.QRect(160, 40, 61, 21))
        self.radioButton.setObjectName("radioButton")
        self.label_2 = QtWidgets.QLabel(self.tab2)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 81, 16))
        self.label_2.setObjectName("label_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab2)
        self.radioButton_3.setGeometry(QtCore.QRect(150, 200, 61, 21))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab2)
        self.radioButton_4.setGeometry(QtCore.QRect(150, 230, 61, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.CoustomizedFilter = QtWidgets.QPushButton(self.tab2)
        self.CoustomizedFilter.setGeometry(QtCore.QRect(40, 210, 88, 27))
        self.CoustomizedFilter.setObjectName("CoustomizedFilter")
        self.QTab.addTab(self.tab2, "")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(240, -20, 20, 600))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textEdit1_1 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit1_1.setGeometry(QtCore.QRect(40, 350, 30, 30))
        self.textEdit1_1.setObjectName("textEdit1_1")
        self.textEdit1_2 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit1_2.setGeometry(QtCore.QRect(70, 350, 30, 30))
        self.textEdit1_2.setObjectName("textEdit1_2")
        self.textEdit1_3 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit1_3.setGeometry(QtCore.QRect(100, 350, 30, 30))
        self.textEdit1_3.setObjectName("textEdit1_3")
        self.textEdit1_4 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit1_4.setGeometry(QtCore.QRect(130, 350, 30, 30))
        self.textEdit1_4.setObjectName("textEdit1_4")
        self.textEdit1_5 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit1_5.setGeometry(QtCore.QRect(160, 350, 30, 30))
        self.textEdit1_5.setObjectName("textEdit1_5")
        self.textEdit2_5 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit2_5.setGeometry(QtCore.QRect(160, 380, 30, 30))
        self.textEdit2_5.setObjectName("textEdit2_5")
        self.textEdit2_4 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit2_4.setGeometry(QtCore.QRect(130, 380, 30, 30))
        self.textEdit2_4.setObjectName("textEdit2_4")
        self.textEdit2_3 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit2_3.setGeometry(QtCore.QRect(100, 380, 30, 30))
        self.textEdit2_3.setObjectName("textEdit2_3")
        self.textEdit2_2 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit2_2.setGeometry(QtCore.QRect(70, 380, 30, 30))
        self.textEdit2_2.setObjectName("textEdit2_2")
        self.textEdit2_1 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit2_1.setGeometry(QtCore.QRect(40, 380, 30, 30))
        self.textEdit2_1.setObjectName("textEdit2_1")
        self.textEdit3_5 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit3_5.setGeometry(QtCore.QRect(160, 410, 30, 30))
        self.textEdit3_5.setObjectName("textEdit3_5")
        self.textEdit3_4 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit3_4.setGeometry(QtCore.QRect(130, 410, 30, 30))
        self.textEdit3_4.setObjectName("textEdit3_4")
        self.textEdit3_3 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit3_3.setGeometry(QtCore.QRect(100, 410, 30, 30))
        self.textEdit3_3.setObjectName("textEdit3_3")
        self.textEdit3_2 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit3_2.setGeometry(QtCore.QRect(70, 410, 30, 30))
        self.textEdit3_2.setObjectName("textEdit3_2")
        self.textEdit3_1 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit3_1.setGeometry(QtCore.QRect(40, 410, 30, 30))
        self.textEdit3_1.setObjectName("textEdit3_1")
        self.textEdit4_5 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit4_5.setGeometry(QtCore.QRect(160, 440, 30, 30))
        self.textEdit4_5.setObjectName("textEdit4_5")
        self.textEdit4_4 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit4_4.setGeometry(QtCore.QRect(130, 440, 30, 30))
        self.textEdit4_4.setObjectName("textEdit4_4")
        self.textEdit4_3 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit4_3.setGeometry(QtCore.QRect(100, 440, 30, 30))
        self.textEdit4_3.setObjectName("textEdit4_3")
        self.textEdit4_2 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit4_2.setGeometry(QtCore.QRect(70, 440, 30, 30))
        self.textEdit4_2.setObjectName("textEdit4_2")
        self.textEdit4_1 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit4_1.setGeometry(QtCore.QRect(40, 440, 30, 30))
        self.textEdit4_1.setObjectName("textEdit4_1")
        self.textEdit5_5 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit5_5.setGeometry(QtCore.QRect(160, 470, 30, 30))
        self.textEdit5_5.setObjectName("textEdit5_5")
        self.textEdit5_4 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit5_4.setGeometry(QtCore.QRect(130, 470, 30, 30))
        self.textEdit5_4.setObjectName("textEdit5_4")
        self.textEdit5_3 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit5_3.setGeometry(QtCore.QRect(100, 470, 30, 30))
        self.textEdit5_3.setObjectName("textEdit5_3")
        self.textEdit5_2 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit5_2.setGeometry(QtCore.QRect(70, 470, 30, 30))
        self.textEdit5_2.setObjectName("textEdit5_2")
        self.textEdit_25 = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit_25.setGeometry(QtCore.QRect(40, 470, 30, 30))
        self.textEdit_25.setObjectName("textEdit_25")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuClear = QtWidgets.QMenu(self.menuBar)
        self.menuClear.setObjectName("menuClear")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionClear_All = QtWidgets.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuClear.addAction(self.actionClear)
        self.menuClear.addAction(self.actionClear_All)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuClear.menuAction())

        self.retranslateUi(MainWindow)
        self.QTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.histogram.setText(_translate("MainWindow", "Greylevel Histogram"))
        self.OTSU.setText(_translate("MainWindow", "OTSU"))
        self.label.setText(_translate("MainWindow", "0"))
        self.QTab.setTabText(self.QTab.indexOf(self.tab1), _translate("MainWindow", "Histogram"))
        self.MeanFilter.setText(_translate("MainWindow", "Mean"))
        self.MedianFilter.setText(_translate("MainWindow", "Median"))
        self.GaussianFilter.setText(_translate("MainWindow", "Gaussian"))
        self.radioButton_2.setText(_translate("MainWindow", "5 x 5"))
        self.radioButton.setText(_translate("MainWindow", "3 x 3"))
        self.label_2.setText(_translate("MainWindow", "Coustomized"))
        self.radioButton_3.setText(_translate("MainWindow", "3 x 3"))
        self.radioButton_4.setText(_translate("MainWindow", "5 x 5"))
        self.CoustomizedFilter.setText(_translate("MainWindow", "Go!"))
        self.QTab.setTabText(self.QTab.indexOf(self.tab2), _translate("MainWindow", "Filter"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuClear.setTitle(_translate("MainWindow", "Clear"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClear.setText(_translate("MainWindow", "Clear View"))
        self.actionClear_All.setText(_translate("MainWindow", "Clear All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

