# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../GUI/mainwindow.ui'
#
# Created: Sun Jun  5 22:54:51 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.View1 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View1.setGeometry(QtCore.QRect(260, 0, 256, 256))
        self.View1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View1.setObjectName("View1")
        self.View2 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View2.setGeometry(QtCore.QRect(530, 0, 256, 256))
        self.View2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View2.setObjectName("View2")
        self.View4 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View4.setGeometry(QtCore.QRect(530, 270, 256, 256))
        self.View4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View4.setObjectName("View4")
        self.View3 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View3.setGeometry(QtCore.QRect(260, 270, 256, 256))
        self.View3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View3.setObjectName("View3")
        self.QTab = QtWidgets.QTabWidget(self.centralWidget)
        self.QTab.setGeometry(QtCore.QRect(10, 0, 230, 321))
        self.QTab.setObjectName("QTab")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.GrayvalueScrollBar = QtWidgets.QScrollBar(self.tab1)
        self.GrayvalueScrollBar.setGeometry(QtCore.QRect(210, 0, 16, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GrayvalueScrollBar.sizePolicy().hasHeightForWidth())
        self.GrayvalueScrollBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.GrayvalueScrollBar.setFont(font)
        self.GrayvalueScrollBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.GrayvalueScrollBar.setMouseTracking(False)
        self.GrayvalueScrollBar.setMaximum(255)
        self.GrayvalueScrollBar.setPageStep(8)
        self.GrayvalueScrollBar.setProperty("value", 0)
        self.GrayvalueScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.GrayvalueScrollBar.setObjectName("GrayvalueScrollBar")
        self.histogram = QtWidgets.QPushButton(self.tab1)
        self.histogram.setGeometry(QtCore.QRect(50, 60, 80, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram.sizePolicy().hasHeightForWidth())
        self.histogram.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histogram.setFont(font)
        self.histogram.setObjectName("histogram")
        self.OTSU = QtWidgets.QPushButton(self.tab1)
        self.OTSU.setGeometry(QtCore.QRect(50, 160, 80, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OTSU.setFont(font)
        self.OTSU.setObjectName("OTSU")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setGeometry(QtCore.QRect(167, 130, 41, 20))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setContentsMargins(0, 0, 0, 0)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.QTab.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.MeanFilter = QtWidgets.QPushButton(self.tab2)
        self.MeanFilter.setGeometry(QtCore.QRect(20, 30, 88, 27))
        self.MeanFilter.setObjectName("MeanFilter")
        self.MedianFilter = QtWidgets.QPushButton(self.tab2)
        self.MedianFilter.setGeometry(QtCore.QRect(20, 60, 88, 27))
        self.MedianFilter.setObjectName("MedianFilter")
        self.GaussianFilter = QtWidgets.QPushButton(self.tab2)
        self.GaussianFilter.setGeometry(QtCore.QRect(20, 90, 88, 27))
        self.GaussianFilter.setObjectName("GaussianFilter")
        self.line_2 = QtWidgets.QFrame(self.tab2)
        self.line_2.setGeometry(QtCore.QRect(0, 130, 231, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.tab2)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 81, 16))
        self.label_2.setObjectName("label_2")
        self.CoustomizedFilter = QtWidgets.QPushButton(self.tab2)
        self.CoustomizedFilter.setGeometry(QtCore.QRect(70, 210, 88, 27))
        self.CoustomizedFilter.setObjectName("CoustomizedFilter")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab2)
        self.plainTextEdit.setGeometry(QtCore.QRect(150, 30, 75, 25))
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_3 = QtWidgets.QLabel(self.tab2)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 31, 25))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab2)
        self.label_4.setGeometry(QtCore.QRect(110, 60, 41, 25))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(150, 60, 75, 25))
        self.plainTextEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.QTab.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.BinaryErosion = QtWidgets.QPushButton(self.tab3)
        self.BinaryErosion.setGeometry(QtCore.QRect(20, 50, 88, 27))
        self.BinaryErosion.setObjectName("BinaryErosion")
        self.BinaryDilation = QtWidgets.QPushButton(self.tab3)
        self.BinaryDilation.setGeometry(QtCore.QRect(120, 50, 88, 27))
        self.BinaryDilation.setObjectName("BinaryDilation")
        self.line_3 = QtWidgets.QFrame(self.tab3)
        self.line_3.setGeometry(QtCore.QRect(0, 130, 231, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.DistanceTransform = QtWidgets.QPushButton(self.tab3)
        self.DistanceTransform.setGeometry(QtCore.QRect(50, 160, 131, 27))
        self.DistanceTransform.setObjectName("DistanceTransform")
        self.Skeleton = QtWidgets.QPushButton(self.tab3)
        self.Skeleton.setGeometry(QtCore.QRect(50, 200, 131, 27))
        self.Skeleton.setObjectName("Skeleton")
        self.SkeletonResoration = QtWidgets.QPushButton(self.tab3)
        self.SkeletonResoration.setGeometry(QtCore.QRect(50, 240, 131, 27))
        self.SkeletonResoration.setObjectName("SkeletonResoration")
        self.QTab.addTab(self.tab3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(0, 130, 231, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.GrayDilation = QtWidgets.QPushButton(self.tab)
        self.GrayDilation.setGeometry(QtCore.QRect(120, 50, 88, 27))
        self.GrayDilation.setObjectName("GrayDilation")
        self.GrayErosion = QtWidgets.QPushButton(self.tab)
        self.GrayErosion.setGeometry(QtCore.QRect(20, 50, 88, 27))
        self.GrayErosion.setObjectName("GrayErosion")
        self.Skeleton_2 = QtWidgets.QPushButton(self.tab)
        self.Skeleton_2.setGeometry(QtCore.QRect(50, 160, 131, 27))
        self.Skeleton_2.setObjectName("Skeleton_2")
        self.Skeleton_3 = QtWidgets.QPushButton(self.tab)
        self.Skeleton_3.setGeometry(QtCore.QRect(50, 200, 131, 27))
        self.Skeleton_3.setObjectName("Skeleton_3")
        self.Skeleton_4 = QtWidgets.QPushButton(self.tab)
        self.Skeleton_4.setGeometry(QtCore.QRect(50, 240, 131, 27))
        self.Skeleton_4.setObjectName("Skeleton_4")
        self.QTab.addTab(self.tab, "")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(240, -20, 20, 600))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.plainTextEdit1_1 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit1_1.setGeometry(QtCore.QRect(20, 350, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit1_1.setFont(font)
        self.plainTextEdit1_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit1_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit1_1.setCenterOnScroll(False)
        self.plainTextEdit1_1.setObjectName("plainTextEdit1_1")
        self.plainTextEdit1_2 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit1_2.setGeometry(QtCore.QRect(50, 350, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit1_2.setFont(font)
        self.plainTextEdit1_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit1_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit1_2.setCenterOnScroll(False)
        self.plainTextEdit1_2.setObjectName("plainTextEdit1_2")
        self.plainTextEdit1_3 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit1_3.setGeometry(QtCore.QRect(80, 350, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit1_3.setFont(font)
        self.plainTextEdit1_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit1_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit1_3.setCenterOnScroll(False)
        self.plainTextEdit1_3.setObjectName("plainTextEdit1_3")
        self.plainTextEdit1_4 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit1_4.setGeometry(QtCore.QRect(110, 350, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit1_4.setFont(font)
        self.plainTextEdit1_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit1_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit1_4.setCenterOnScroll(False)
        self.plainTextEdit1_4.setObjectName("plainTextEdit1_4")
        self.plainTextEdit1_5 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit1_5.setGeometry(QtCore.QRect(140, 350, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit1_5.setFont(font)
        self.plainTextEdit1_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit1_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit1_5.setCenterOnScroll(False)
        self.plainTextEdit1_5.setObjectName("plainTextEdit1_5")
        self.plainTextEdit2_5 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit2_5.setGeometry(QtCore.QRect(140, 380, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit2_5.setFont(font)
        self.plainTextEdit2_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit2_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit2_5.setCenterOnScroll(False)
        self.plainTextEdit2_5.setObjectName("plainTextEdit2_5")
        self.plainTextEdit2_4 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit2_4.setGeometry(QtCore.QRect(110, 380, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit2_4.setFont(font)
        self.plainTextEdit2_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit2_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit2_4.setCenterOnScroll(False)
        self.plainTextEdit2_4.setObjectName("plainTextEdit2_4")
        self.plainTextEdit2_3 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit2_3.setGeometry(QtCore.QRect(80, 380, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit2_3.setFont(font)
        self.plainTextEdit2_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit2_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit2_3.setCenterOnScroll(False)
        self.plainTextEdit2_3.setObjectName("plainTextEdit2_3")
        self.plainTextEdit2_2 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit2_2.setGeometry(QtCore.QRect(50, 380, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit2_2.setFont(font)
        self.plainTextEdit2_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit2_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit2_2.setCenterOnScroll(False)
        self.plainTextEdit2_2.setObjectName("plainTextEdit2_2")
        self.plainTextEdit2_1 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit2_1.setGeometry(QtCore.QRect(20, 380, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit2_1.setFont(font)
        self.plainTextEdit2_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit2_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit2_1.setCenterOnScroll(False)
        self.plainTextEdit2_1.setObjectName("plainTextEdit2_1")
        self.plainTextEdit3_5 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit3_5.setGeometry(QtCore.QRect(140, 410, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit3_5.setFont(font)
        self.plainTextEdit3_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit3_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit3_5.setCenterOnScroll(False)
        self.plainTextEdit3_5.setObjectName("plainTextEdit3_5")
        self.plainTextEdit3_4 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit3_4.setGeometry(QtCore.QRect(110, 410, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit3_4.setFont(font)
        self.plainTextEdit3_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit3_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit3_4.setCenterOnScroll(False)
        self.plainTextEdit3_4.setObjectName("plainTextEdit3_4")
        self.plainTextEdit3_3 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit3_3.setGeometry(QtCore.QRect(80, 410, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit3_3.setFont(font)
        self.plainTextEdit3_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit3_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit3_3.setCenterOnScroll(False)
        self.plainTextEdit3_3.setObjectName("plainTextEdit3_3")
        self.plainTextEdit3_2 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit3_2.setGeometry(QtCore.QRect(50, 410, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit3_2.setFont(font)
        self.plainTextEdit3_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit3_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit3_2.setCenterOnScroll(False)
        self.plainTextEdit3_2.setObjectName("plainTextEdit3_2")
        self.plainTextEdit3_1 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit3_1.setGeometry(QtCore.QRect(20, 410, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit3_1.setFont(font)
        self.plainTextEdit3_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit3_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit3_1.setCenterOnScroll(False)
        self.plainTextEdit3_1.setObjectName("plainTextEdit3_1")
        self.plainTextEdit4_5 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit4_5.setGeometry(QtCore.QRect(140, 440, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit4_5.setFont(font)
        self.plainTextEdit4_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit4_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit4_5.setCenterOnScroll(False)
        self.plainTextEdit4_5.setObjectName("plainTextEdit4_5")
        self.plainTextEdit4_4 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit4_4.setGeometry(QtCore.QRect(110, 440, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit4_4.setFont(font)
        self.plainTextEdit4_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit4_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit4_4.setCenterOnScroll(False)
        self.plainTextEdit4_4.setObjectName("plainTextEdit4_4")
        self.plainTextEdit4_3 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit4_3.setGeometry(QtCore.QRect(80, 440, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit4_3.setFont(font)
        self.plainTextEdit4_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit4_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit4_3.setCenterOnScroll(False)
        self.plainTextEdit4_3.setObjectName("plainTextEdit4_3")
        self.plainTextEdit4_2 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit4_2.setGeometry(QtCore.QRect(50, 440, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit4_2.setFont(font)
        self.plainTextEdit4_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit4_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit4_2.setCenterOnScroll(False)
        self.plainTextEdit4_2.setObjectName("plainTextEdit4_2")
        self.plainTextEdit4_1 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit4_1.setGeometry(QtCore.QRect(20, 440, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit4_1.setFont(font)
        self.plainTextEdit4_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit4_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit4_1.setCenterOnScroll(False)
        self.plainTextEdit4_1.setObjectName("plainTextEdit4_1")
        self.plainTextEdit5_5 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit5_5.setGeometry(QtCore.QRect(140, 470, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit5_5.setFont(font)
        self.plainTextEdit5_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit5_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit5_5.setCenterOnScroll(False)
        self.plainTextEdit5_5.setObjectName("plainTextEdit5_5")
        self.plainTextEdit5_4 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit5_4.setGeometry(QtCore.QRect(110, 470, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit5_4.setFont(font)
        self.plainTextEdit5_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit5_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit5_4.setCenterOnScroll(False)
        self.plainTextEdit5_4.setObjectName("plainTextEdit5_4")
        self.plainTextEdit5_3 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit5_3.setGeometry(QtCore.QRect(80, 470, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit5_3.setFont(font)
        self.plainTextEdit5_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit5_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit5_3.setCenterOnScroll(False)
        self.plainTextEdit5_3.setObjectName("plainTextEdit5_3")
        self.plainTextEdit5_2 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit5_2.setGeometry(QtCore.QRect(50, 470, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit5_2.setFont(font)
        self.plainTextEdit5_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit5_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit5_2.setCenterOnScroll(False)
        self.plainTextEdit5_2.setObjectName("plainTextEdit5_2")
        self.plainTextEdit5_1 = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit5_1.setGeometry(QtCore.QRect(20, 470, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.plainTextEdit5_1.setFont(font)
        self.plainTextEdit5_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit5_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit5_1.setCenterOnScroll(False)
        self.plainTextEdit5_1.setObjectName("plainTextEdit5_1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_2.setGeometry(QtCore.QRect(180, 420, 61, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_1 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_1.setGeometry(QtCore.QRect(180, 390, 61, 21))
        self.radioButton_1.setObjectName("radioButton_1")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuClear = QtWidgets.QMenu(self.menuBar)
        self.menuClear.setObjectName("menuClear")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClear_View = QtWidgets.QAction(MainWindow)
        self.actionClear_View.setObjectName("actionClear_View")
        self.actionClear_All = QtWidgets.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuClear.addAction(self.actionClear_View)
        self.menuClear.addAction(self.actionClear_All)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuClear.menuAction())

        self.retranslateUi(MainWindow)
        self.QTab.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.histogram.setText(_translate("MainWindow", "Histogram"))
        self.OTSU.setText(_translate("MainWindow", "OTSU"))
        self.label.setText(_translate("MainWindow", "0"))
        self.QTab.setTabText(self.QTab.indexOf(self.tab1), _translate("MainWindow", "Histogram"))
        self.MeanFilter.setText(_translate("MainWindow", "Mean"))
        self.MedianFilter.setText(_translate("MainWindow", "Median"))
        self.GaussianFilter.setText(_translate("MainWindow", "Gaussian"))
        self.label_2.setText(_translate("MainWindow", "Coustomized"))
        self.CoustomizedFilter.setText(_translate("MainWindow", "Go!"))
        self.label_3.setText(_translate("MainWindow", "Size:"))
        self.label_4.setText(_translate("MainWindow", "Alpha:"))
        self.QTab.setTabText(self.QTab.indexOf(self.tab2), _translate("MainWindow", "Filter"))
        self.BinaryErosion.setText(_translate("MainWindow", "Erosion"))
        self.BinaryDilation.setText(_translate("MainWindow", "Dilation"))
        self.DistanceTransform.setText(_translate("MainWindow", "Distance Transform"))
        self.Skeleton.setText(_translate("MainWindow", "Skeleton"))
        self.SkeletonResoration.setText(_translate("MainWindow", "Skeleton Restoration"))
        self.QTab.setTabText(self.QTab.indexOf(self.tab3), _translate("MainWindow", "B-M"))
        self.GrayDilation.setText(_translate("MainWindow", "Dilation"))
        self.GrayErosion.setText(_translate("MainWindow", "Erosion"))
        self.Skeleton_2.setText(_translate("MainWindow", "Edge Detection"))
        self.Skeleton_3.setText(_translate("MainWindow", "Reconstruction"))
        self.Skeleton_4.setText(_translate("MainWindow", "Gradient"))
        self.QTab.setTabText(self.QTab.indexOf(self.tab), _translate("MainWindow", "G-M"))
        self.plainTextEdit1_1.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit1_2.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit1_3.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit1_4.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit1_5.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit2_5.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit2_4.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit2_3.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit2_2.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit2_1.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit3_5.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit3_4.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit3_3.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit3_2.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit3_1.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit4_5.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit4_4.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit4_3.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit4_2.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit4_1.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit5_5.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit5_4.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit5_3.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit5_2.setPlainText(_translate("MainWindow", "0"))
        self.plainTextEdit5_1.setPlainText(_translate("MainWindow", "0"))
        self.radioButton_2.setText(_translate("MainWindow", "5 x 5"))
        self.radioButton_1.setText(_translate("MainWindow", "3 x 3"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuClear.setTitle(_translate("MainWindow", "Clear"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClear_View.setText(_translate("MainWindow", "Clear View"))
        self.actionClear_All.setText(_translate("MainWindow", "Clear All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

