# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../GUI/mainwindow.ui'
#
# Created: Sun May 29 17:00:45 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.View1 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View1.setGeometry(QtCore.QRect(260, 0, 256, 256))
        self.View1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View1.setObjectName("View1")
        self.View2 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View2.setGeometry(QtCore.QRect(530, 0, 256, 256))
        self.View2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View2.setObjectName("View2")
        self.View3 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View3.setGeometry(QtCore.QRect(530, 270, 256, 256))
        self.View3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View3.setObjectName("View3")
        self.View4 = QtWidgets.QGraphicsView(self.centralWidget)
        self.View4.setGeometry(QtCore.QRect(260, 270, 256, 256))
        self.View4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.View4.setObjectName("View4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 230, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.GrayvalueScrollBar = QtWidgets.QScrollBar(self.tab1)
        self.GrayvalueScrollBar.setGeometry(QtCore.QRect(210, 0, 16, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GrayvalueScrollBar.sizePolicy().hasHeightForWidth())
        self.GrayvalueScrollBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.GrayvalueScrollBar.setFont(font)
        self.GrayvalueScrollBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.GrayvalueScrollBar.setMouseTracking(False)
        self.GrayvalueScrollBar.setMaximum(255)
        self.GrayvalueScrollBar.setPageStep(8)
        self.GrayvalueScrollBar.setProperty("value", 0)
        self.GrayvalueScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.GrayvalueScrollBar.setObjectName("GrayvalueScrollBar")
        self.histogram = QtWidgets.QPushButton(self.tab1)
        self.histogram.setGeometry(QtCore.QRect(20, 60, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram.sizePolicy().hasHeightForWidth())
        self.histogram.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.histogram.setFont(font)
        self.histogram.setObjectName("histogram")
        self.OTSU = QtWidgets.QPushButton(self.tab1)
        self.OTSU.setGeometry(QtCore.QRect(40, 180, 88, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OTSU.setFont(font)
        self.OTSU.setObjectName("OTSU")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setGeometry(QtCore.QRect(167, 130, 41, 20))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setContentsMargins(0, 0, 0, 0)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.tabWidget.addTab(self.tab2, "")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(240, -20, 20, 600))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.histogram.setText(_translate("MainWindow", "Greylevel Histogram"))
        self.OTSU.setText(_translate("MainWindow", "OTSU"))
        self.label.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Histogram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

